#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:20:00
#PBS -N app-classifiedfibertractstats
#PBS -V

set -e
set -x

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./msa/main

echo "moving output file under ./output"
mkdir -p output
mv output_FiberStats.csv output

echo "all done"
